spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  application:
    sms:
      gateway:
        type: aws
        aws:
          region: us-east-1
  platform:
    security:
      type: jwt

